export {default as HomePage} from './Home'
export {default as RegisterPage} from './Register'
export {default as ProfilePage} from './Profile'
export {default as VerifyPage} from './Verify'
export {default as LoginPage} from './Login'
export {default as PageNotFound} from './NotFound'